apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: quay-user-pass
spec:
  encryptedData:
    password: AgDBRak67OXX1lCYe7DseIPqlbKYtuXaWS4H6t3uGbGBnHVi988qrIEC2wrltpfaI39KADCKZppjBSG7iVSBiBeF43+GVvygoftF9hF2RuZiOZtMvLhhJT8QjjJIYP4djmOz7qLRa98E6VJhFEw8AdY3m/jUz3RdGIwWFEIhJbxjv3HJ+K8hlaEV0Qiz0opQpwR6cisu3o5/n5/8Isd4QWFUJHg1ZkxTzWa0XXzNH5mspKwYpuGDPwksumRrQPRpbMCC+g8C5+7PvvhNJGV/rCwm4zXrD6WSOVnlD5wAdTvqZySCH7YtruxB119WSq9v2611VPufPAVlfxVgI13dWkSfL+Vs5P+qbfFZY0aqzOGkfr4Gi2e3T5qpRYpeAHd8s2Ysjps/h2wMslRwjYQY4mAv0I40GINsdQCz4paIU4ju/GHbZMfp/P3Ut9q0j5/6AoQ88s111oi1O9+kCv11WYh3DAV3fX/4lSFXybM6CUWyxQOVMmHlIi9IFEOVSHMWFPkOnuTfWCN9i7mKK8GX462qSm5IPSePZZ4YdElRLJecoRaMmuhHwkMDKEN+x2/p0QUm9D7dQLFp776rvEhOKfuo//MG9NokeZxT272O9TOaS8ahajZEF1OVWZj38EwgqMbkx+4jQ7r6s1s4p2o7ciNbI60Ky6mZ/FE82IeM/i33yCLfM9RKON4MGqS/kJUYGoyobPtmIIzWF9iIEiwpuL6QNaoGkKAHHy5UP7PEo/wUCtVrEkT7CdN2L3DtVIe1NJ2FcMwYlAC1LQVXiZLl70iq
    username: AgBYCV5DZdMhX4KFOGAIT1itXM/PejKloLHcUfWeVqltjG3yVI1NqR53u1qeDz/UCgIMri90cEif0hvFGQ00kXbz9NJhxPAFtG+nlbffagfCFmHow0zrwxNGfVFKA0xnoqRN6zNBF50KzFqurctwJ6KO0/e8Ap3cJPIUQilfHI1qpay3f/PDULK9tARhe4oc3JL05P0jpzuWZ0vTsqS+ebzN8erxWvoG2M/eKI7wCihoTbQ/RIno5FMeJXKbgRe0KHwvvwJIITxWW7DeXpcJD6Y7pnE9UC374ip9se23zQzkDaz5x0YYsBEahxfRd6BhNXs4v0MNe2C8alsJAchMIHBOc55JQCt0BXi5KTz9Lu8db1ZfzwJWx4eIP9Vknnhs+CvBmm6Y2ETwC5mF9FS3gdlRa4BGPYe3XWum62763ZuQUF/OCIdr4Ezylb/dfmqjVRnYVqb+/qOh9WhbHGqcvU1Ei5vxsZ4Bu51kiegLYZ1u132T5SxZAX0wHSTkIe8EkE6sFFqDhtMRuWWO8MNgxnTucOpMWho+S4FFgqg/6CQvM6JtyOgZab8de9S+DrqNmbgZgUik17WKmmq+F/rZb1Eh/QDGm0lc3hMxqXRaWCRk2UjTJpoQe9iEPE74Ltd9Qm0c8MrLHvR1X8T8cW9tItPSi8pM3UclYxnNxhoRnAqY09kfZ3ZVk+RWOsTrm8bsBR7Pvz1ylgNQf1WCmQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/docker-0: https://quay.io
      creationTimestamp: null
      name: quay-user-pass
    type: kubernetes.io/basic-auth
